name: Delete Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Delete branch
      if: github.event.pull_request.merged == true
      run: git push origin --delete ${{ github.event.pull_request.head.ref }}
